# Generated by Django 4.2 on 2023-05-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0013_alter_collectionplan_weight"),
    ]

    operations = [
        migrations.RemoveField(model_name="location", name="address",),
    ]
